name: build-nvgpu-pkg

on:
  push:
    branches:
      - tegra-nvgpu
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}-nvgpu
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nvgpu-pkg
        run: |
          docker buildx build \
            --file=Pkgfile \
            --target=nvgpu-pkg \
            --platform=linux/arm64 \
            --provenance=false \
            --progress=plain \
            --push \
            --tag=ghcr.io/${{ github.repository_owner }}/nvgpu-pkg:${{ github.sha }} \
            .
